### ISSUE TITLE
[New Feature]: Want to add the footer !

### ISSUE THREAD

**Issue by SiddharthaArepalli** [ChromeGaming/Dot-Box#103]
### 🎮 feature Request

I want add the footer with all the social media links of ur  and  adding the copyright at the end of the footer 
![Screenshot 2024-05-13 233051](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/140429954/3b22b898-e433-40c7-981b-182ae9c1e014)
here is the example

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Akansha1409** [comment]
Hey, there! , i think it is a great project
I want to make it more attractive by adding footer with some social media icons and copyrights.
kindly assign me this issue.

**Comment by SiddharthaArepalli** [comment]
@Durgesh4993  On It  🚀 !!

**Comment by Sajiyasiddiqui** [comment]
I want to work on this . Please assign to me.
