### ISSUE TITLE
[Enhancement]: Add time limit for each player's turn

### ISSUE THREAD

**Issue by ankiiitagupta** [ChromeGaming/Dot-Box#105]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

For each player's turn there is no limit which may lead to time wastage. 

### Describe the solution you'd like

To manage time, we can add time limit for each player's turn using javascript. This will ensure that player completes his move within specified time and if not, another player's turn starts.

### Select program in which you are contributing

GSSoC'24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

please assign this issue to me under GSSoC'24.

**Comment by KARTHIK174** [comment]
please assign me this issue,i want to work on this.i have knowledge on this
