### ISSUE TITLE
[Documentation Bug]: Add Screenshot of Dot Box to README File for Enhanced Project Understanding

### ISSUE THREAD

**Issue by AsmitaMishra24** [ChromeGaming/Dot-Box#109]
### Describe the bug ✍️

The README lacks a crucial screenshot of the Dot Box game, hindering user engagement and project comprehension.

### Provide step by step information reproduce the bug 📄

**Steps to Reproduce:**

1. Open the Dot Box project's README.
2. Notice the absence of a game screenshot.
3. Reflect on how this omission affects users' understanding and interest.

**Proposed Solution:**
- To remedy this bug:
1. Capture a clear Dot Box game screenshot.
2. Edit for clarity and highlight key features.
3. Place the screenshot near the top of the README.
4. Accompany it with a brief, informative caption.
5. Update the README in the project repository.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by AsmitaMishra24** [comment]
I am a contributor for GSSoC'24, so please assign me this issue.

**Comment by PrashantAnand03** [comment]
I would like to work on this issue, please assign this to me

**Comment by Rashi563** [comment]
Please assign me this issue under GSSOC'24
