### ISSUE TITLE
Improving the UI of home page

### ISSUE THREAD

**Issue by Manishar55** [ChromeGaming/Dot-Box#111]
### 🎮 feature Request

feature logic and basic description:
I want to improve the UI of the home page, as the page is looking so simple and black and white  I want to make it more attractive by adding some beautiful colors and some hover effect.
Can you please assign this task to me

![Screenshot 2024-05-14 093552](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/154615478/7fb0500b-135d-4a5f-9f5c-2f9fdbee30f2)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Manishar55 Could you please explain more what you want to do....

**Comment by Manishar55** [comment]
> @Manishar55 Could you please explain more what you want to do....


I want to improve the UI of the home page, the home page of a site should look attractive because it creates a good first impression, makes visitors want to stay and explore more, and helps them quickly find what they're looking for. An appealing design can also make the site look more professional and trustworthy.
as the page is looking so simple and black and white I want to make it more attractive by adding some beautiful colors and some hover effect.

**Comment by Durgarani8115** [comment]
The main page needs to be more attractive to engage users. Suggestions include:

- Modernize the layout
- Update the color scheme
- Add high-quality images
- Improve typography
- Include subtle animations

Please assign this to me. Thanks!

**Comment by Paavni-Goyal** [comment]
Can you please assign me this under gssoc'24.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Manishar55

**Comment by Seejal03** [comment]
assign me this issue under GSSOC'24

**Comment by harshcodesit** [comment]
Hey @Durgesh4993 
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .
