### ISSUE TITLE
Settings button

### ISSUE THREAD

**Issue by sdas1311** [ChromeGaming/Dot-Box#128]
### 🎮 feature Request

A settings button to on and off the sound and exit the game

### Point down the features

feature points
the settings button will have :
1) Toggle sound on/off button 
2) background changer
3) exit game
### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sdas1311** [comment]
Please assign me this issue and also put GSSoC level-2 label

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
