### ISSUE TITLE
[Enhancement]:  Catchy phrases and animations to the game

### ISSUE THREAD

**Issue by rajvaidyanath27** [ChromeGaming/Dot-Box#129]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

 i can give a very good css to the UI of the game

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shrexxs** [comment]
can you assign me this issue?

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
