### ISSUE TITLE
[New Feature]: Updating the home page and addition of a navbar 

### ISSUE THREAD

**Issue by VaibhavS0710** [ChromeGaming/Dot-Box#131]
### 🎮 feature Request

I will modify the home page to look more interactive and I will add one navbar from where the players can read instruction. 

### Point down the features

feature points
1. Updating the home page
2.  Adding a navbar for menu, instruction etc. .

<img width="959" alt="Screenshot 2024-05-15 110602" src="https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/138979375/3f5eccaf-fc68-40cd-9be9-8cc3399bb1c2">

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by LordVaibhav** [comment]
Please @Durgesh4993 assign me this issue under GSSoC'24 label. I really want to work upon this issue.

**Comment by VaibhavS0710** [comment]
@Lovelyfin00 please assign me this issue under the label GSSoC'24.

**Comment by Lovelyfin00** [comment]
Hi @VaibhavS0710 
There’s no need for nab bar since there’s no other links we want to redirect them to

**Comment by VaibhavS0710** [comment]
@Lovelyfin00 Navbar will be for adding home page, custom settings, instructions, etc..

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
