### ISSUE TITLE
[New Feature]: Add reset button

### ISSUE THREAD

**Issue by anubhootipandey** [ChromeGaming/Dot-Box#132]
### 🎮 feature Request

After the player wins, to head back to its initial position, we have to add reset functionality. 
![Screenshot 2024-05-15 120248](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/114290029/5a3be39f-6b1f-4036-aa22-4cd61815ec37)

### Point down the features

feature points:
adding reset button
on clicking the button, it will reset the game.  

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ShahHetviIT** [comment]
I'm excited about leading the Dot-Box project. With my expertise in HTML, CSS, JavaScript, and ReactJS, I'm ready to make a substantial impact on this endeavor. Please assign me to this issue through GSSOC.

**Comment by NAhmad231** [comment]
Pease assign the label .
I would like to work on this , please assign this to me.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
