### ISSUE TITLE
[New Feature]: Home page should appear attractive.

### ISSUE THREAD

**Issue by GitNinja-bcd** [ChromeGaming/Dot-Box#134]
### 🎮 feature Request

The homepage should be colorful, and we can add a navbar where we can include some icons using CSS. We can also add a demo video showing how the game is played.  

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by avikaagarwalll** [comment]
please assign me I can do this

**Comment by GitNinja-bcd** [comment]
Kindly assign me this issue , I will do this .

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
