### ISSUE TITLE
[New Feature]: Add Players name 

### ISSUE THREAD

**Issue by GitNinja-bcd** [ChromeGaming/Dot-Box#135]
### 🎮 feature Request

We can add the Player's name instead of Player1, Player2, etc. , and we can also record the history who always win the game if same players are playing again and again.

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by GitNinja-bcd** [comment]
Kindly assign me this issue.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
