### ISSUE TITLE
[New Feature]: instead of black line each player will make line of the same color as they have been assigned 

### ISSUE THREAD

**Issue by Kriagr23** [ChromeGaming/Dot-Box#136]
### 🎮 feature Request

Feature logic and basic description:
as the user clicks is black line Is created instead of a back line each line of the respective player color will look more attractive and easier to understand 
Kindly assign this issue to me 

### Point down the features

feature points:
make the game more colorful and enrich the UX
 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ShahHetviIT** [comment]
I'm excited about leading the Dot-Box project. With my expertise in HTML, CSS, JavaScript, and ReactJS, I'm ready to make a substantial impact on this endeavor. Please assign me to this issue through GSSOC.

**Comment by neevgit25** [comment]
Ready to dive into the Dot-Box project . I'm well-versed in HTML, CSS, JavaScript, and ReactJS, and I'm eager to contribute. Please assign me to this issue via GSSOC.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
