### ISSUE TITLE
Change the font color of home page

### ISSUE THREAD

**Issue by anshulsoni4** [ChromeGaming/Dot-Box#140]
### 🎮 feature Request

The color needs to be light, for better ui

### Point down the features

![Uploading image.png…]()

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by maniranjan2023** [comment]
I kindly request to be assigned to this project. Thank you for considering my request.

**Comment by ishap11** [comment]
Please assign me this issue under GSSoC'24.

**Comment by suhani-sharmaa** [comment]
please assign me this issue

**Comment by SantoshiVerma** [comment]
hey @anshulsoni4 please assign me this issue  I can the color to be light, for better ui. i want to work on this issue.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by anshulsoni4** [comment]
i see nobody has assigned me this issue, kindly do it ASAP
