### ISSUE TITLE
[Enhancement]: Improve UI of game

### ISSUE THREAD

**Issue by neel815** [ChromeGaming/Dot-Box#142]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hello using my HTML,CSS skills I can change your game's UI. I will do this this Contribution under GSSoC'24.

### Describe the solution you'd like

Solution steps (1) Update Color Scheme: Use more vibrant and modern colors.
(2) Typography: Choose better fonts for headings and content.
(3) Button Styles: Make buttons more visually appealing.
(4) Background Video: Ensure the background video looks seamless.
(5) Animations: Add subtle animations to enhance interactivity.
![improvedui](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/119388300/db037f46-31bf-43c0-89f5-51fb39213874)
It will look like this hope you like it!!

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by harshcodesit** [comment]
I can contribute with code pen animated buttons and add more interactive elements to the UI

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by neel815** [comment]
Bro,Why you have closed this issue without assigning?
