### ISSUE TITLE
[Enhancement]: Use of better font family and font colors

### ISSUE THREAD

**Issue by Sheersh01** [ChromeGaming/Dot-Box#146]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

 Use of better font family and font colors

### Describe the solution you'd like

1: Use a better font family which will go with the theme and not some default and basic fonts.
2: Use of better color palette for overall better visuals

### Select program in which you are contributing

GSSoC' 24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by maniranjan2023** [comment]
I kindly request to be assigned to this project. Thank you for considering my request.

**Comment by neevgit25** [comment]
I expect to be assigned to this project. Thank you for considering my request.

**Comment by suhani-sharmaa** [comment]
please assign me this issue.
