### ISSUE TITLE
[New Feature]: A Back Button and A Reset/Restart Button

### ISSUE THREAD

**Issue by Sheersh01** [ChromeGaming/Dot-Box#147]
### 🎮 feature Request

A back button to go back to home screen and a reset button to restart the game.

### Point down the features

A back button to go back to home screen and a reset button to restart the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by narayani9120** [comment]
Kindly assign this issue to me, under gssoc .

**Comment by sanikadighe16** [comment]
I want to work on this issue, please assign this issue to me.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
