### ISSUE TITLE
[New Feature]: Add undo button

### ISSUE THREAD

**Issue by CoderGirl2844** [ChromeGaming/Dot-Box#148]
### 🎮 feature Request

Add Undo button

### Point down the features

This undo button would allow the player to correct wrong move

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanikadighe16** [comment]
I can add the undo button, kindly assign this issue to me.

**Comment by mythri1010** [comment]
hey, this is mythri, i would like to add this feature with a good suitable design for the button. I have worked with these projects for hackathons, so i have the needed experience in this. Can you pls assign this to me under GSSOC'24 @Arpit1499 
thank you

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
