### ISSUE TITLE
[Enhancement]:  Clear Rules for the Game

### ISSUE THREAD

**Issue by Oindrila-Bhowmik** [ChromeGaming/Dot-Box#152]
### Game enhancement:
The instructions are vague regarding how the player needs to play the game. A step-by-step rule can help players become aware of the rules and play the game effectively.

### Solution steps:
 I can provide a step-by-step process of playing the game in the 'Instructions' part of the Game setting page, that makes the players completely aware of the ruleset governing the game.

_Program under which I'm contributing_: **GSSoC'24**. Marking the level of the issue under the appropriate Label, please assign me the issue to work on.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
