### ISSUE TITLE
[New Feature]: Play Again option and score tracking

### ISSUE THREAD

**Issue by ritu713** [ChromeGaming/Dot-Box#153]
### 🎮 feature Request

**Issue**
1. There is no option for users to play the same game again or change the stats of the game and play again.
2. In continuous games, we can add the feature of keeping track of player one and two's scores.

**Additional details**
Contributing under GSSOC

### Point down the features

1. A replay button. 
2. Clicking the replay button will ask the user if they want to play again with the same box and number of players
3. Corresponding redirect

_Additional_
Keep track of scores of each number and number of matches played.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
