### ISSUE TITLE
[Bug]: Homepage can be made more appealing

### ISSUE THREAD

**Issue by Bhavishya2601** [ChromeGaming/Dot-Box#154]
### Give a brief about the bug ✍️

The homepage alignment is not correct, it is going vertically out of frame and there is no actual need for horizontal scroll.
I wanna correct and moreover want to work on the color combination as the test is not that appealing

https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/147748752/c8f0f0d0-c15c-4bad-b829-88e4372d076b

### What is the expected behavior? 🤔

It is making the website less appealing and by improving it, it would surely make it more appealing 

It is scrolling vertically

### Provide step by step information reproduce the bug 📄

I would fix the bug

Hope you would assign this task to me

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by KashishRathore** [comment]
I would like to work on this issue. Please assign this task to me as the label of Gssoc24 and level.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
