### ISSUE TITLE
Visibility issue of the text color

### ISSUE THREAD

**Issue by somrima-09** [ChromeGaming/Dot-Box#155]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
**Visibility issue of the text color
Improving the Font and Color and Style of the texts int the main page**

![Screenshot 2024-05-16 222859](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/137212792/b8581044-2c61-4a80-a72c-d7dbc6a68c45)

### Describe the solution you'd like

Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by suhani-sharmaa** [comment]
can you please assign me this issue.

**Comment by LAKSHYA1509** [comment]
Hi as a Frontend Developer with a Knack of UI/UX .. I think i can do it !! Please assign it to me

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
