### ISSUE TITLE
[Feature]: Start New Game

### ISSUE THREAD

**Issue by gobbledy-gook** [ChromeGaming/Dot-Box#157]
### 🎮 feature Request

- **Description**: Once the game is over, then the players must be given the option to start a new game. 
- **Logic**: Once the winner is announced, we can display a button at the end `Start New Game` which will take them to the `HomePage` where they can again select the box sizes and the number of players.

### Point down the features

- Start New Game

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by gobbledy-gook** [comment]
Please assign this issue to me. Thanks !

**Comment by vansh-sardana** [comment]
Kindly assign this issue to me.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
