### ISSUE TITLE
[Enhancement]: Giving Rank for players while playing

### ISSUE THREAD

**Issue by aswin98855** [ChromeGaming/Dot-Box#162]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

I want to add Ranking of the players based on their points. Ranks will be changed when the points are changed.

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/116991167/6c23c18f-da4d-42c7-a147-91969851c79f)

Based on above image the ranking order will be :

Rank       Players
1             Player-3
2             Player-5
3             Player-6
4             Player-1
5             Player-2
6             Player-4

In 4,5,6 positions, the rank will be given in the order of players.

Please assign this issue to me under gssoc24

### Describe the solution you'd like

Solution steps:

Initially Ranks are given in player number order.

When players are playing, While they are gaining points, The rank for that players will be changed. Based on the points the rank will be given. The players with highest points is ranked 1 and so on. If players having same points, The rank will be given in the order of players.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aswin98855** [comment]
Please Assign this issue to me under gssoc24

**Comment by aswin98855** [comment]
Please Assign this issue to me under gssoc24

The output looks like

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/116991167/ccf7451c-f111-41bd-8698-5673b8cd0662)

**Comment by aswin98855** [comment]
I want to work on this Issue Under GSSOC, Kindly Assign me this Issue. @Lovelyfin00  @Durgesh4993

**Comment by Lovelyfin00** [comment]
This ia a great idea! It should show when the game has been won by any of the players not while the game is still ongoing @aswin98855

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by hars-21** [comment]
@ayush-t02 Please assign it to me
