### ISSUE TITLE
[Enhancement]    Changing the font colour and font family 

### ISSUE THREAD

**Issue by carolinelall** [ChromeGaming/Dot-Box#163]
### 🎮 Enhancement

I want to change the font colour and font family as it is not visible on dark background. Inorder, to enhance the text and make it look more visible and attractive. 

### Point down the features

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/51926095/a9b4d059-c9cb-4038-a555-af0c8d78ad5f)

@Lovelyfin00  @Durgesh4993  Sir, Please assign me this issue, I would love to work on it.
I have experience in the relevant technologies, which I believe will be valuable in addressing the issue effectively.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Lovelyfin00** [comment]
What color do you want to change it to?
Remember it’s dark theme that we’re using so the color has to follow

**Comment by carolinelall** [comment]
> What color do you want to change it to? Remember it’s dark theme that we’re using so the color has to follow

@Lovelyfin00  Sir you're absolutely right that font needs to be according to the dark theme .. 
Keeping this in mind, i just want to slightly minimise the colour contrast 
and the website will look like ( after changing the colour) 
![WhatsApp Image 2024-05-17 at 2 47 05 PM](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/51926095/8f6a8ee3-a7d0-47a2-908b-4b3a0440d352)

**Comment by Lovelyfin00** [comment]
This looks fine 
@Durgesh4993 what do you think about this?

**Comment by Aman0413** [comment]
Hi @carolinelall,

I'd like to work on this bug. Please assign it to me.

Thanks,
Aman Verma

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
