### ISSUE TITLE
[New Feature]: Music on/off button 

### ISSUE THREAD

**Issue by sdas1311** [ChromeGaming/Dot-Box#164]
### 🎮 feature Request

feature logic and basic description

- a toggle button to turn music on or off by clicking it, 
- by applying simple javascript event handler.

### Point down the features

feature points

- music on/off button

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by SakiraAli1115** [comment]
Can you please assign me this issue?

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
