### ISSUE TITLE
[New Feature]: Exit button in the game

### ISSUE THREAD

**Issue by 3simransharma** [ChromeGaming/Dot-Box#166]
### 🎮 feature Request

I have added the exit button in this game, so that if user wants to add more players or does not want to play, then they can exit in the middle of the game. I know that we can simply refresh the page for that but it'll be user-friendly and more easy for the users.

Please checkout my pull request #165 and please add this feature under the GSSOC'24 tag.

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
