### ISSUE TITLE
[New Feature]: Adding Login page

### ISSUE THREAD

**Issue by saketh-05** [ChromeGaming/Dot-Box#167]
### 🎮 feature Request

I want to login/Sign up page to the Game, so that players can save their data i.e high score, number of times played, number of wins, etc. This will be great enhancement and the website will be more modernized. Please assign this issue to me under GSSoC'24.

### Point down the features

Login page. 
Save useful data of players.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SakiraAli1115** [comment]
Can you please assign me this issue?

**Comment by Aman0413** [comment]
Hi @saketh-05 ,

I'd like to work on this bug. Please assign it to me.

Thanks,
Aman Verma

**Comment by Ipeeka** [comment]
I want to work on this issue.Please assign to me

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
