### ISSUE TITLE
[New Feature]: Profile page of a Player

### ISSUE THREAD

**Issue by saketh-05** [ChromeGaming/Dot-Box#168]
### 🎮 feature Request

Most of the players wish to have a profile to showcase their skill and talent to their friends. So I want to add a Profile page with player's name, basic details, login info, and more importantly number of wins, win rate, number of games played and many more.
So Please assign this issue to me under GSSoC'24.

### Point down the features

Profile page.
Modernizing website.
Players attraction.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by saketh-05** [comment]
This will be a very good feature after including Tournament feature.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
