### ISSUE TITLE
[New Feature]: Responsiveness of website.

### ISSUE THREAD

**Issue by abhiperfect** [ChromeGaming/Dot-Box#171]
### 🎮 feature Request

Enhance website responsiveness for optimal viewing on all devices. Utilize flexible layouts, mobile-friendly navigation, and touch-friendly design. Ensure images and videos resize seamlessly. Optimize CSS and JavaScript for improved load times, particularly on mobile devices.

![Screenshot 2024-05-17 230438](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/114478676/e28f95dd-881c-414f-8912-50572e6741a4)

### Point down the features

1. **Responsive Layout**: Ensure content adjusts seamlessly for different screen sizes.
2. **Responsive Navigation**: Implement mobile-friendly navigation, like a hamburger menu.
3. **Touch-Friendly Design**: Design interactive elements for easy touchscreen use.
4. **Flexible Media**: Ensure images and videos resize appropriately for various screens.
5. **Performance Optimization**: Optimize CSS and JavaScript for faster load times, especially on mobile.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by YukiP7** [comment]
I would also like to work on this under Gssoc'24

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
