### ISSUE TITLE
[New Feature]: Creating a leaderboard.

### ISSUE THREAD

**Issue by abhiperfect** [ChromeGaming/Dot-Box#173]
### 🎮 feature Request

Players can view who won or lost in each round.

### Point down the features

1. **Round Results Display**: Show winners and losers for each round.
2. **Clear Visibility**: Ensure easy access to round outcomes for all players.
3. **Concise Presentation**: Provide a straightforward overview of winners and losers.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
