### ISSUE TITLE
[New Feature]: Generate a room ID.

### ISSUE THREAD

**Issue by abhiperfect** [ChromeGaming/Dot-Box#174]
### 🎮 feature Request

Enable the generation of unique room IDs for match continuation between two players. This feature ensures match results are stored in the leaderboard, allowing players to resume matches seamlessly.

#### Requirements:
1. **Room ID Generation**: Develop a system to generate unique room IDs.
2. **Match Resumption**: Allow players to enter room IDs to resume matches.
3. **Leaderboard Integration**: Ensure match results are associated with room IDs in the leaderboard.
4. **Security Measures**: Implement measures to maintain the security and confidentiality of room IDs.

#### Benefits:
The room ID generation feature streamlines match continuation, providing players with an efficient way to resume matches while ensuring their results are accurately recorded in the leaderboard.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
