### ISSUE TITLE
[New Feature]: Shift the website to React.js.

### ISSUE THREAD

**Issue by abhiperfect** [ChromeGaming/Dot-Box#175]
### 🎮 feature Request

Migrate the website to React.js for enhanced frontend development. Utilize React's component-based architecture and state management for efficient UI rendering and dynamic content updates. Improve code organization, developer productivity, and website performance.

### Point down the features

1. **Migration**: Shift website frontend to React.js.
   
2. **Components**: Implement modular components.
   
3. **State**: Utilize React's state management.
   
4. **Rendering**: Leverage React's virtual DOM for dynamic content.

5. **Optimization**: Enhance performance with React's rendering.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
