### ISSUE TITLE
[Bug]: Improving the readability of home page

### ISSUE THREAD

**Issue by Aashi19234** [ChromeGaming/Dot-Box#178]
### Give a brief about the bug ✍️

Currently the text in home page is not at all readable due to its light font color.

### What is the expected behavior? 🤔

I want it to make it more readable to enhance the user experience.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by mehrun171** [comment]
I want to work on this issue..so please assign me this task

**Comment by mehrun171** [comment]
please add the gssoc level1 label

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
