### ISSUE TITLE
add some good design in  page and give restart resume feature in it[New Feature]: 

### ISSUE THREAD

**Issue by Sameena10** [ChromeGaming/Dot-Box#179]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ankitamishra17** [comment]
Please can you assign me this issue?

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
