### ISSUE TITLE
[Enhancement]: Responsiveness to game 

### ISSUE THREAD

**Issue by YukiP7** [ChromeGaming/Dot-Box#180]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement : Your game is not responsive which is hard to play on phone and it is not applicable for all device users . Making your game responsive can work well for mobile phone users and you can connect with more people as it is a great game to play in college lectures .
![Screenshot 2024-05-18 194223](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/109288720/6b786a7e-dfed-4817-b3c8-8025ec770216)

### Describe the solution you'd like

Solution steps: Making it responsive for all types of devices . Please assign me this issue and label it as Gssoc with appropriate level .

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by YukiP7** [comment]
Hey, @ayush-t02Can you please assign me this issue? I am participating in GSSOC'24 and would love to resolve this soon.

**Comment by gobbledy-gook** [comment]
Similar to issue #171

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
