### ISSUE TITLE
[Enhancement]: I can add interactive bg to the home page, and can modify start menu, main game page.

### ISSUE THREAD

**Issue by VaibhavS0710** [ChromeGaming/Dot-Box#184]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

I can add a good bg to the home page and can modify the start menu, and add undo button to main game page.
I am attaching some sample pictures how our page will look like.
![home bg](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/138979375/3f8dea1c-27d8-4d90-87a6-837f601b7799)
<img width="372" alt="start menu" src="https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/138979375/bf005a91-2a33-410e-9d13-fe3bc096bc74">

### Describe the solution you'd like

Solution steps:
1. Addition of a good bg to the home page which can make our home page look more interactive.
2. Modifying the start menu which will help the user to select the game settings in a more easier way.
3. Can make the main game page more interactive and can add undo button.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VaibhavS0710** [comment]
@Lovelyfin00 please assign this issue to me under GSSoC'24.

**Comment by Lovelyfin00** [comment]
Hi @VaibhavS0710 
We have already merged a PR addressing the background video

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
