### ISSUE TITLE
[Enhancement]: improve home page UI

### ISSUE THREAD

**Issue by sau-mili** [ChromeGaming/Dot-Box#188]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

UI enhancement

### Describe the solution you'd like

Solution steps
Mofification in CSS requiredfont colors, theme button colors and animation

contributing in GSSOC'24

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
