### ISSUE TITLE
[Enhancement]: A Stylish Makeover with Bold Fonts!

### ISSUE THREAD

**Issue by driyash9881** [ChromeGaming/Dot-Box#190]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/118407844/975533d6-9315-474b-bbfc-b5d056552970)
Currently, the Dot-Box game homepage lacks visual appeal and fails to captivate users. To address this, we'll start by selecting a contemporary font family that reflects the game's theme and personality. We'll adjust font sizes appropriately to maintain a balanced visual hierarchy and improve legibility across different screen sizes.

### Describe the solution you'd like

Solution steps step 1- We'll streamline the layout, ensuring a clean and uncluttered interface.
Step 2 -Clear call-to-action buttons will guide users seamlessly through the game's features. 
Step 3-Consistent use of spacing and alignment will enhance readability and create a cohesive look.

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by driyash9881** [comment]
Please assign this issue to me

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by srivalli1239** [comment]
Please assign the issue I am a Gssoc'24 Contributor and I will work on it
