### ISSUE TITLE
[New Feature]: Adding "Create online room" option

### ISSUE THREAD

**Issue by StephenStolk** [ChromeGaming/Dot-Box#193]
### 🎮 feature Request

Adding a button "Create online room" to allow players from anywhere to compete against each other online from any device.

Tech Stack:
Socketio - to create a game server , and online room creation support (websockets)

Sample to understand:

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/134587780/0c012179-a264-420f-8f57-05c5bb576e5c)

### Point down the features

- Adding "Create online room" feature
- Creating a shareable link that can be shared among friends through social media through which they can join the room
- Players can join through link or room id shared

**I want to take up this issue.** 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Lovelyfin00** [comment]
Hello @StephenStolk 
This is too complicated for what we have now. The game isn't going in this direction currently.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
