### ISSUE TITLE
[DOCS]: Write Installation Guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [ChromeGaming/Dot-Box#196]
Draft a comprehensive guide that outlines the step-by-step process for installing and setting up Dot-Box locally on different operating systems (Windows, macOS, Linux).

Could you please assign me.

Significance of the changes made
By providing clear installation instructions, we can lower the barrier for new users to get started with Draw-it-out, encouraging wider adoption of the application.

Thank You

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
