### ISSUE TITLE
[New Feature]: Adding Navbar to make it user friendly and add multiples options.

### ISSUE THREAD

**Issue by HarshitGupta1511** [ChromeGaming/Dot-Box#198]
### 🎮 feature Request

feature logic and basic description -  Adding Navbar will let user know all the features or options game offer at the top only.

### Point down the features

feature points - I want to add Navbar to add features like  user guide , instruction , change theme , play online or home page buttons at the top . I will do this using HTML  and CSS and its properties and will also add attractive effects to each button. please assign me this task/project @ayush-t02 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
nice feature, focus on the UI, try to keep it simple

**Comment by HarshitGupta1511** [comment]
> nice feature, focus on the UI, try to keep it simple

Sure Sir! working on it

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by vctigerrfab** [comment]
i want to work on this project, kindly assign this issue to me

**Comment by vctigerrfab** [comment]
i want to work on this project, kindly assign this issue to me

**Comment by ayush-t02** [comment]
@vctigerrfab this issue is already assigned, work on some other issue
