### ISSUE TITLE
[Bug]: Validation of the inserted values in Rows, Columns, and Players. 

### ISSUE THREAD

**Issue by ParthNakum21** [ChromeGaming/Dot-Box#205]
### Give a brief about the bug ✍️

It is allowing the user to enter in the game even if he/she does not enter the values in the given range.

### What is the expected behavior? 🤔

It should not allow user to enter in the game. It should show a message to enter a valid value.

### Provide step by step information reproduce the bug 📄

Validate the value and show the message. 

I'm interested in contributing to the project by solving this problem. 
Could you please assign this task to me under GSSoC'24 with appropriate level?

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by ParthNakum21** [comment]
Hello @Amancoder-01, I want to work on above mentioned issue. Could you please assign this task to me?
