### ISSUE TITLE
💡[Front Page]: I will create a main Landing Page for the website 

### ISSUE THREAD

**Issue by Priyanshu2743** [ChromeGaming/Dot-Box#207]
### feature logic and basic description
As a new user, we can provide him with a good beginning by making him land on the main page
I will create a Main Landing page for the website that a user will be shown once he/she opens the website

### feature points
It will create a good user-friendly environment for the user
Great Interaction with the user

I will make it more interactive and user friendly with smooth running

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by Priyanshu2743** [comment]
### I want to say that I want to improve the UI of the website under gssoc
kindly assign this issue to me under gssoc2024 and add labels of levels

**Comment by Stylyan** [comment]
can you assign me to this project

**Comment by Durgesh4993** [comment]
@Stylyan Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
