### ISSUE TITLE
[New Feature]: Redesign the Game Page

### ISSUE THREAD

**Issue by Vimall03** [ChromeGaming/Dot-Box#222]
### 🎮 feature Request

The proposal is to completely redesign the game page's background and layout to enhance user experience and visual appeal. The new design will aim to be more intuitive, engaging, and aesthetically pleasing, ensuring a modern look and feel.

### Point down the features

feature points
- Improve loading times and performance.
- Redesign buttons, menus, and other interactive elements to be more visually appealing and user-friendly.

### Current Game Page

![Screenshot 2024-05-23 143800](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/109758195/518664fd-6530-48ae-9704-263e12338c2f)

### Proposed Re-design

![Screenshot 2024-05-23 151105](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/109758195/8aaec415-5230-4c7a-9559-c92dda6f9f14)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)

**Comment by Vimall03** [comment]
@ayush-t02 kindly review the PR #306 for this issue.
