### ISSUE TITLE
[Enhancement]: Home icon on Game

### ISSUE THREAD

**Issue by kashisharora9462** [ChromeGaming/Dot-Box#223]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Currently, there is no home icon to navigate back to the main page once the game has started. This can lead to a frustrating user experience, as users may find it difficult to return to the main page.

![Uploading Screenshot 2024-05-23 175600.png…]()

### Describe the solution you'd like

Solution steps
To improve user navigation between the home page and the game, I propose adding a user-friendly home icon that links directly to the home page. This will provide a seamless experience for users, making it easier for them to switch between the home page and the game.

Please consider assigning me this task under GSsoc'24.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Amancoder-01** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
