### ISSUE TITLE
feat: Log in page 

### ISSUE THREAD

**Issue by AnikethDeb2004** [ChromeGaming/Dot-Box#229]
### 🎮 feature Request

Make a landing page where user need to log in first !

### Point down the features

it would be great if the feature be implemented

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by akarshi19** [comment]
Please assign this issue to me under GSSoC'24
