### ISSUE TITLE
[Bug]: The new "Theme feature" has introduced a major bug.

### ISSUE THREAD

**Issue by anindita-panda** [ChromeGaming/Dot-Box#233]
### Give a brief about the bug ✍️

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/148877270/5964ac95-192e-4a69-9eec-5673cfd571b3)

There are two scroll bars, which are not meant to be at all. 
Also, on scrolling we can see two overlapping background at once (Refer the attached image).

### What is the expected behavior? 🤔

The scroll bars are not supposed to be there and only the theme applied by user should be applied independently.

### Provide step by step information reproduce the bug 📄

1. Scroll down to the bottom of the page.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by anindita-panda** [comment]
please assign this to me under the gssoc'24 label, will do my best to solve it

**Comment by ridayeah** [comment]
please assign this issue to me under the gssoc'24 label

**Comment by Prachi309** [comment]
Please assign this project to me
