### ISSUE TITLE
[Bug]: Dot-Box game is not at all responsive for mobile  devices

### ISSUE THREAD

**Issue by mondalsurojit** [ChromeGaming/Dot-Box#237]
### Give a brief about the bug ✍️

Description
The Dot-Box game is not at all responsive for mobile devices.

![Screenshot (296)](https://github.com/GameSphere-MultiPlayer/Community-Page/assets/114282267/a57acb79-3472-4f59-98a2-93804ff5654f)

### What is the expected behavior? 🤔

Description
The Dot-Box game must have been responsive, and adaptive to all type of mobile screen sizes 

### Provide step by step information reproduce the bug 📄

Description

Open the site: [https://gamesphere-multiplayer.github.io/Dot-Box/](https://gamesphere-multiplayer.github.io/Dot-Box/) in a mobile device

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### Urgency (Optional)

High priority

**Comment by akarshi19** [comment]
Please assign this issue to me under GSSoC'24

**Comment by mondalsurojit** [comment]
@Durgesh4993 Hello sir, I went through the code, and found that the code currently is highly interlinked. When I try to fix something, its directly or indirectly affecting the other part of the code.
To fix this, I have to refactor several things, like I have to seperate the settings page from the game page (I will use local storage to store the settings values and once the player click 'Start', it will take the user to the game page and in the game page the settings values will be retrieved from the local storage). 
Seperation of logic is very important as more contributions will make this very complex overtime. If I have your permission, I will work on to fix the whole setup, as fixing just a part using hacks, will cause problem now or later.

**Comment by Durgesh4993** [comment]
@mondalsurojit delete your old code and reclone repo again

**Comment by mondalsurojit** [comment]
@Durgesh4993 I did it. But nothing is different...

So should I go ahead with my above proposition...?

**Comment by ayush-t02** [comment]
@mondalsurojit as for the refactoring issue, just make it a rule to "pull before push". Always work on the most updated code.

**Comment by mondalsurojit** [comment]
@ayush-t02 Ok sir...

**Comment by mondalsurojit** [comment]
@ayush-t02 Sir, can you please also update the level tag here (PR)...
