### ISSUE TITLE
[New Feature]:  removing horizontal scrollbar

### ISSUE THREAD

**Issue by ujj654** [ChromeGaming/Dot-Box#239]
### 🎮 feature Request

removing the horizontal scroll bar from the game because it doesn't giving the better user experience and it also looks distracting for the users. 

Screenshot:-

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/81877649/c8e5077a-5fe8-4b92-8399-bbbe11953ace)

### Point down the features

1.  removing the horizontal scroll bar 
2.  it will improve the user experience
3.  it also improve the looking of the website

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ujj654** [comment]
Please assign me this issue. #GSSoc'24

**Comment by lassmara** [comment]
Please assign me this issue.
