### ISSUE TITLE
[New Feature]: The background picture and the color of the font of the front page arent complimenting

### ISSUE THREAD

**Issue by Agrima11** [ChromeGaming/Dot-Box#241]
### 🎮 feature Request

the picture is soo filled up and the font is in a dull blue color

### Point down the features

feature points
same as mentioned above

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by akarshi19** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Coder-Prachi** [comment]
@Agrima11  Please assign this issue to me under GSSoC'24
