### ISSUE TITLE
[Bug]: Font Color is too bright to be understood

### ISSUE THREAD

**Issue by noviciusss** [ChromeGaming/Dot-Box#242]
### Give a brief about the bug ✍️

font is silver or white it cannot be seen if typed once hard to unerstand

### What is the expected behavior? 🤔

make it dark either black or grey 

### Provide step by step information reproduce the bug 📄

i will change the input font color to something dark .....assign it to me 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by TitikshyaChanda** [comment]
Please assign me this

**Comment by Coder-Prachi** [comment]
@noviciusss sir, please assign this issue to me . I really want to work on this

**Comment by DiyaMittal02** [comment]
please assign it to me. I want to work on it

**Comment by Harshita2027** [comment]
I want to work on it

**Comment by aasthabagrawal** [comment]
I would love to do it, plz assign it to me.

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by Durgesh4993** [comment]
@noviciusss Could you please explain more what you want to do, if possible you can also add screenshot.
