### ISSUE TITLE
[New Feature]: player hover  the line change color according player theme. 

### ISSUE THREAD

**Issue by Nidhikumrawat** [ChromeGaming/Dot-Box#244]
### 🎮 feature Request

when hover the user color is gray is too confusing which turn.

### Point down the features

- when player hover the indicator change color 
- whenever any player turn ,like Player 1's turn button color is pink , whenever he click on horizontal , vertical indicator those are hover its player color .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manish12-verma** [comment]
Hello ,can you please assign this task to me
