### ISSUE TITLE
add a hover effect on start button..

### ISSUE THREAD

**Issue by shuhaki** [ChromeGaming/Dot-Box#246]
### 🎮 feature Request

feature logic and basic description
add a hover effect on start button.. its give good user interface to user
<img width="505" alt="Screenshot 2024-05-28 at 11 50 02 PM" src="https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/145912232/a0b0f4f0-f9eb-4a5e-affe-6423f1c4c705">

### Point down the features

feature points
add a hover effect on start button.. 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Priyamjain1105** [comment]
Greetings Shuhaki ,
I would like to work on this issue. Please assign this issue to me. I look forward to working with you and contributing towards your organization.
