### ISSUE TITLE
[New Feature]: create a 404 not found page for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [ChromeGaming/Dot-Box#258]
### 🎮 feature Request

create a 404 not found page for the website

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Snehapandey07** [comment]
Hey @Durgesh4993 I would love to work on this issue could you please assign me to this
