### ISSUE TITLE
[New Feature]: Need to improve CSS of buttons.

### ISSUE THREAD

**Issue by soniya-malviy** [ChromeGaming/Dot-Box#266]
### 🎮 feature Request

Need to improve CSS of buttons and functionality to change themes.

### Point down the features

Good UI/UX enhance user experience.Also some button functionality is not working for change themes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by harshcodesit** [comment]
I can work on the issue you can see my work in previous pull request

**Comment by lovelymahor** [comment]
please assign this issue to me, i want to work on this
