### ISSUE TITLE
[Bug]: Working on Design of Buttons 

### ISSUE THREAD

**Issue by aarushi-taori** [ChromeGaming/Dot-Box#268]
### Give a brief about the bug ✍️

Working on Design of Buttons 

![image](https://github.com/ChromeGaming/Dot-Box/assets/113369937/d1d5c281-b89c-4550-8aaa-765fcfbc8580)

### What is the expected behavior? 🤔

The buttons design is only raw css. It should match the theme of the website for uniformity

### Provide step by step information reproduce the bug 📄

Code for Designing of Buttons 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by harshcodesit** [comment]
hey @Durgesh4993 
idea :- the default button designs can be removed and  new CSS should be implemented to make the buttons immersive

please assign me the issue
