### ISSUE TITLE
[New Feature]: Custom Cursor

### ISSUE THREAD

**Issue by Anjaliavv51** [ChromeGaming/Dot-Box#289]
### 🎮 feature Request

feature logic and basic description
Cursors are visual cues that help users understand their mouse position and interactions on a website.

### Point down the features

feature points
1.Enhanced User Experience
2.Personalization and Branding
3.Creative Expression

Screenshot how it looks like

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/f4162b47-edcc-4869-9b68-0013f8898d37)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anjaliavv51** [comment]
please assign this issue.

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by Anjaliavv51** [comment]
Assign me this issue under GSSOC

**Comment by Anjaliavv51** [comment]
@Durgesh4993

**Comment by Anjaliavv51** [comment]
@Durgesh4993 please assign me this under GSSOC
