### ISSUE TITLE
[Enhancement]: To Remove Text-Overlapping

### ISSUE THREAD

**Issue by sailaja-adapa** [ChromeGaming/Dot-Box#310]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to modify the text that appears on the screen like this as you can see this in the image it is overlapping

![dotbox](https://github.com/ChromeGaming/Dot-Box/assets/161804629/cc0f363c-d2a9-42bb-98aa-70340ac2261d)

Can you please assign me this issue under gssoc'24

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by AlokShukl12** [comment]
I want to work on it .Please assign me
