### ISSUE TITLE
[Enhancement]: Set a Background image 

### ISSUE THREAD

**Issue by sailaja-adapa** [ChromeGaming/Dot-Box#311]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a Background image to this page 

![dotboxbg](https://github.com/ChromeGaming/Dot-Box/assets/161804629/979ff1c4-c570-432d-8923-e95b7c28261d)

Can you please assign me this issue under gssoc'24

### Describe the solution you'd like

Solution steps

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
