### ISSUE TITLE
[Enhancement]: FOOTER

### ISSUE THREAD

**Issue by P-lavanya16** [ChromeGaming/Dot-Box#313]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: add footer with a neat structured

### Describe the solution you'd like

Solution steps
using html,css adding footer

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aarushibhatia12** [comment]
i want to work on this issue under gssoc 24

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
