### ISSUE TITLE
[New Feature]: Addition of Confetti button 

### ISSUE THREAD

**Issue by HishitaGupta** [ChromeGaming/Dot-Box#315]
### 🎮 feature Request

Addition of Confetti button that shoots out confettis when a player wins the Game using Confetti JS.
![image](https://github.com/ChromeGaming/Dot-Box/assets/159264060/d468f941-88d4-4c0d-a825-cfeed7034b6a)

### Point down the features

Will enhance the User Experience.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by TanviPoddar** [comment]
Please assign me this issue. I would love to work on it!
