### ISSUE TITLE
[Enhancement]: Adding the players' name

### ISSUE THREAD

**Issue by VijaySamant4368** [ChromeGaming/Dot-Box#32]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: There is no option to display the players' name on the game screen.

### Describe the solution you'd like

Solution steps:
After pressing the 'Start' there should be a screen to enter players' name, that can be shown in game screen, instead of their player number.
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/145102345/fba69b7b-eabd-4efe-9c23-a770f5e05b15)

I can resolve this issue using JavaScript and CSS, and I believe I am qualified to resolve it, so please assign this issue to me under the GSSoC 2024.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by royalrajputayush** [comment]
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by priyal38** [comment]
I have done similar kind of thing in react.js boxes game so please assign me this issue under Gssoc'24. I am really excited to contribute.

**Comment by kvdevlopment** [comment]
Hello, I'm a GSSOC'24 contributor

I would like to work on the same. Can you please assign this to me.

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by Durgesh4993** [comment]
@priyal38 @kvdevlopment @royalrajputayush @Yashc885 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by VijaySamant4368** [comment]
I have sent the pr, kindly please check it.
Thanks

**Comment by VijaySamant4368** [comment]
I am sorry, I had not mentioned the issue number in the pr properly.
Please do check the pr now.
