### ISSUE TITLE
[Bug]: Mute button not working

### ISSUE THREAD

**Issue by shraddhha** [ChromeGaming/Dot-Box#326]
### Give a brief about the bug ✍️

Description
when the mute button is turned off it only mutes the background music but the sound which comes on clicking and when the color being filled remains unmuted

### What is the expected behavior? 🤔

Description
All sounds should be muted when the mute button is clicked.

### Provide step by step information reproduce the bug 📄

Description
By making the suitable changes in the javascript that the event of mute button should be properly handled.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
