### ISSUE TITLE
[Bug]: no home button

### ISSUE THREAD

**Issue by dnyandeepchute** [ChromeGaming/Dot-Box#328]
### Give a brief about the bug ✍️

no home button is present and restart button is working as home button

### What is the expected behavior? 🤔

instead of restart button there should be home button

### Provide step by step information reproduce the bug 📄

replacing restart button by home button.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
