### ISSUE TITLE
There is no exit button showing

### ISSUE THREAD

**Issue by Mounika-Adabala** [ChromeGaming/Dot-Box#333]
## If the player want to exit in the middle of the game, there is no exit button showing over there.
![No exit button](https://github.com/ChromeGaming/Dot-Box/assets/105410061/98f7bc8a-736c-4644-a092-81d433e66fee)
I want to work on this problem.

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ankitamishra17** [comment]
please assign this issue to me under GSSoC'24.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
