### ISSUE TITLE
[Bug]:  The text color is not properly visible

### ISSUE THREAD

**Issue by chaanakyaaM** [ChromeGaming/Dot-Box#334]
### Give a brief about the bug ✍️

Description:
The text of the chrome gaming is not clearly visible at the foot of the homepage.
![image](https://github.com/ChromeGaming/Dot-Box/assets/131477601/3d05f9f3-56c4-48b5-adfa-83d42a4204e1)

and at the gameplay the player1 and player2 text is not syncing with background grey color , it makes the website design a bit odd.
![image](https://github.com/ChromeGaming/Dot-Box/assets/131477601/96e70996-3744-4321-9162-46e1731e8dac)

### What is the expected behavior? 🤔

Description:
Bright colors can to be used in order to fix this bug, just like white color.

### Provide step by step information reproduce the bug 📄

Description:
- I will change the color of the text from dark grey to white on the footer.
- Then i will also change the color of the player1 and player2 text in the game site(to white for better  and easy visibility).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by deepanshi211** [comment]
Hello ,I am interested to work on this?Could you please assign this to me??

**Comment by 2004Tejashree** [comment]
hello, I want to work on this project . Please assign this task to me
