### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by Priti9075** [ChromeGaming/Dot-Box#335]
### 🎮 feature Request

The home page does not have a navbar or footer, and when the game starts, there is no button to return to the homepage. I can add a navbar, footer, and enhance the UI. Please assign me this issue under GSoC '24.

### Point down the features

->navbar with options like 
1.home
2.login
3.contactus
4.about
->footer:

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
