### ISSUE TITLE
Adding light and dark theme

### ISSUE THREAD

**Issue by KARTHIK174** [ChromeGaming/Dot-Box#340]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

We can add light and dark theme for the game website which makes the website more attractive.

### Describe the solution you'd like

We can keep the toggle button to toggle between the light and dark themes.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.
Assign me this issue under GSSoC24.

**Comment by safiya2610** [comment]
Assign me this issue under GSSoC'24, I would like to work on it.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by 2004Tejashree** [comment]
Hii , I want to work on this task . Please assign me.
