### ISSUE TITLE
[New Feature]: show box size 

### ISSUE THREAD

**Issue by SankojuNikitha06** [ChromeGaming/Dot-Box#343]
### 🎮 feature Request

feature logic and basic description:
By showing the different box sizes the people can estimate the time limit to play and select their choice.
And based on the number of people they can choose the box size (like game with 25,, 16, 9, ... boxes)

### Point down the features

feature points : this feature will show the player to select the box size

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by AlokShukl12** [comment]
i want to work on this project [Dot-Box]. please assign me

**Comment by sanchitkhthpalia** [comment]
hello, please assign this issue to me.

**Comment by 2004Tejashree** [comment]
hello , please assign this task to me.
