### ISSUE TITLE
[New Feature]:  Add new dark theme

### ISSUE THREAD

**Issue by Shweta-281** [ChromeGaming/Dot-Box#352]
### 🎮 feature Request

feature logic and basic description
I want to add the new fresh dark theme to look beautiful 

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Shweta-281** [comment]
I want to work this issue.
 Please assign me.

**Comment by 2004Tejashree** [comment]
hey, i want to work on this project so please assign this task to me
