### ISSUE TITLE
[Enhancement]: add animation in homepage 

### ISSUE THREAD

**Issue by sanayamahajan-23** [ChromeGaming/Dot-Box#355]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

### Describe the solution you'd like

i will add animation in homepage to make it more visually appealing.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@sanayamahajan-23 Show some designs
