### ISSUE TITLE
[New Feature]: Creating "ABOUT US" page .

### ISSUE THREAD

**Issue by HarshitGupta1511** [ChromeGaming/Dot-Box#377]
### 🎮 feature Request

feature logic and basic description
Creating about us page which will describe about the project as well as the game.

please assign this task to me @ay

### Point down the features

feature points
I want to add basic information about this open source project , about the developers , and about the Game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aradhyajha** [comment]
Hii sir @HarshitGupta1511 , i want to work on this issue and i will complete it with in a day please assign this task to me
 for this project, first create a new HTML file named about.html and structure it with appropriate sections such as company history, mission, team, and contact information. Integrate this new page into your website's navigation menu by updating the menu links in your main HTML or layout file. Style the page using CSS to ensure it matches the overall website theme. If your site uses a backend framework, create a corresponding route to render the "About Us" page. Test the page for responsiveness and accessibility

**Comment by Aradhyajha** [comment]
![about](https://github.com/ChromeGaming/Dot-Box/assets/130289875/1cfd11bf-749a-44fa-8769-9d3c887aa9d5)

**Comment by HarshitGupta1511** [comment]
please assign this to me
 @ayush-t02

**Comment by ayush-t02** [comment]
@Aradhyajha please work on some existing issue or create an issue and tag me for assigning.

**Comment by Aradhyajha** [comment]
Ok sir

**Comment by Aradhyajha** [comment]
Sir I mentioned u in 2 issue please assign it to me I will complete these
as soon as possible for me issue no. 380 and 388
