### ISSUE TITLE
Adding FAQ section [New Feature]: 

### ISSUE THREAD

**Issue by rajlaxmi03** [ChromeGaming/Dot-Box#38]
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MrCodYrohit** [comment]
@rajlaxmi03 @Durgesh4993 I follow all contributing guidelines and code of conduct for this project, can you please label it properly as per GSSOC' 24 guidelines, I am willing to fix this issues ASAP.

**Comment by Shubhra-Narang** [comment]
Kindly assign me this issue ,I can contribute to this

**Comment by Durgesh4993** [comment]
@MrCodYrohit @Shubhra-Narang Please raise any other issue, i'll assign you
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by ayush-t02** [comment]
@rajlaxmi03 you need to edit the issue template, there is no description

**Comment by sambangiadharsh** [comment]
i am gssoc contributor please assign this work to me.
