### ISSUE TITLE
[New Feature]: Background Colour of box which appears on the home page

### ISSUE THREAD

**Issue by AnshikaAg03** [ChromeGaming/Dot-Box#384]
### 🎮 feature Request

feature logic and basic description : The current colour of the box is yellow and orange which looks quite dull with the blue background , 

### Point down the features

feature points:
I would like to change the below colours from yellow and orange to some good combination of colours.
![Dot img](https://github.com/ChromeGaming/Dot-Box/assets/122719744/77c735b7-2fd3-4747-9dcb-7d2e96a5a952)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by AnshikaAg03** [comment]
@ayush-t02 please assign me this issue

**Comment by ayush-t02** [comment]
this isnt a significant change, brainstorm something better.
