### ISSUE TITLE
[Bug]: Start Button is not working

### ISSUE THREAD

**Issue by Durgesh4993** [ChromeGaming/Dot-Box#390]
### Give a brief about the bug ✍️

Open for Contributors

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aradhyajha** [comment]
hello air @ayush-t02 i want to wok on this issue please assign this task to me

**Comment by ayush-t02** [comment]
take your time, dont try to rush it since it is a level3 issue.

**Comment by Aradhyajha** [comment]
ok sir .. thankyou for assigning it

**Comment by Aradhyajha** [comment]
@ayush-t02 .. sir.. can u explain me little bit  how to proceed on this issue, actually i am not going to understand that how start button is not working because even i clicked on the start button its working ..so can u please  guide me what exactly i need to do?

**Comment by Aradhyajha** [comment]
sir.. i think start button is working , there is some problem with reset button ..i think reset button is not working so may i need to work  on it

**Comment by ayush-t02** [comment]
@Aradhyajha yes I think the start button has been fixed via a different PR. you may work on reset button

**Comment by Aradhyajha** [comment]
Ok sir thank you

**Comment by Aradhyajha** [comment]
@ayush-t02 sir .. as you told to work on reset button  so almost i have fixed that one.. so sir this one is issue no. 391 so can you assigned it to me so that while doing pr i can mention issue no #391

**Comment by ayush-t02** [comment]
@Aradhyajha the issue was already assigned to someone and they resolved it before your PR. I think you should stop searching for issues in the issues tab, create issues. In the discord server I had added 3 issues that you like to work on, check them out.
