### ISSUE TITLE
[Bug]: correct the home page layout

### ISSUE THREAD

**Issue by Prakrati1907** [ChromeGaming/Dot-Box#394]
### Give a brief about the bug ✍️

the home pages has clashes with layout.
will correct them
![Screenshot 2024-06-22 223408](https://github.com/ChromeGaming/Dot-Box/assets/120261907/44f4589b-a697-484d-bf6f-5e392f240c70)

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aradhyajha** [comment]
hello sir @ayush-t02 .. please assign this issue to me..
i will complete this as soon as possible

**Comment by Prakrati1907** [comment]
@ayush-t02 please assign this to me

**Comment by VijaySamant4368** [comment]
Can you please mention me when the new layout has been committed, as I want to do additional features on home screen, but doing it currently would lead to headaches during conflict resolve

**Comment by VijaySamant4368** [comment]
I am sorry, I didn't notice that you were assigned the same issue. I have closed my issue and pr. I can help by saying that they will ask you to  make the following changes, as they asked the same to me:
 - your navbar design needs improvements, make it more modern, no need to backgrounds to the anchors.
 - the maximise box is white, totally contrasting the div.
 Once again I am sorry for the trouble I may have caused you.

**Comment by Prakrati1907** [comment]
@VijaySamant4368
 Sure, No issues, Thanks for the improvements, will consider it .
