### ISSUE TITLE
[Enhancement]: Home page Layout

### ISSUE THREAD

**Issue by VijaySamant4368** [ChromeGaming/Dot-Box#396]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Currently the home page layout is a total mess. I tried to correct it without raising an issue, and looks like I was successful. Instead of scrapping it altogether, I tried to improve upon the existing one only. If you think that this will suffice, assign the issue to me, and I would be able to send a pr.
Thanks either way.

### Describe the solution you'd like

Earlier Layout:
![image](https://github.com/ChromeGaming/Dot-Box/assets/145102345/5cb1948f-b9d2-479d-a106-4e674c8ed5dc)

After my changes:
![image](https://github.com/ChromeGaming/Dot-Box/assets/145102345/926b361b-69b3-4244-9851-75973f65e45b)
![image](https://github.com/ChromeGaming/Dot-Box/assets/145102345/ddd2fa46-7457-471c-bdd7-a04316d5b8a2)
I am not sure whether to keep background color, and if so which color.

The only downside I believe is that I had to remove some boxes from the "▂ ▄ ▅ ▆ ▇ █ MAXIMISE BOXES!! █ ▇ ▆ ▅ ▄ ▂" 

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VijaySamant4368** [comment]
Please do assign the level label

**Comment by ayush-t02** [comment]
1. the footer is supposed to be at the bottom
2. your navbar design needs improvements, make it more modern, no need to backgrounds to the anchors.
3. the maximise box is white, totally contrasting the div.
