### ISSUE TITLE
[Enhancement]: Validating The Input fields and Removing Increment/Decrement Icon

### ISSUE THREAD

**Issue by srinidhifd** [ChromeGaming/Dot-Box#41]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement - Validate the input fields , Remove Increment/Decrement icon , Add Reset button beside start button
![Screenshot 2024-05-11 135538](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/93462562/7a7feb1f-533f-426a-a4be-a063754da74e)

### Describe the solution you'd like

Solution steps - 1) if values are not within the range , we can disable the start button or give an alert to give input values .
2)Remove the default increment/decrement in the input field to make UI look better
3)We can add Reset values button beside start , if user wants to reset all the input values in homepage

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Abhay152002** [comment]
I want to work on this issue, please assign it to me under Gssoc'24.

**Comment by srinidhifd** [comment]
So i have mentioned the fixes and enhancements to be done above - Please assign this  issue to me under GSsoc'24 and add relevant label as well

**Comment by Durgesh4993** [comment]
@Abhay152002  Please raise any other issue, i'll assign you
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
