### ISSUE TITLE
[Bug]: Theme not changing and no theme works on the game page

### ISSUE THREAD

**Issue by ayush-t02** [ChromeGaming/Dot-Box#412]
### Give a brief about the bug ✍️

The theme is not changing in the homepage. There is no theme visible in the gamepage.

### What is the expected behavior? 🤔

The theme should change when a different theme is selected. Add atleast 3 themes.

### Provide step by step information reproduce the bug 📄

Just launch the application and try to change the theme via dropbox.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by hars-21** [comment]
@ayush-t02 Assign me please. I'll work on it.
