### ISSUE TITLE
[New Feature]: FAQs ICON at Navbar

### ISSUE THREAD

**Issue by taniya542** [ChromeGaming/Dot-Box#418]
### 🎮 feature Request

Faqs section can be added to Navbar which can be linked to a page where FAQs can be answered.

### Point down the features

feature points:
Accessibility: It provides quick access to answers for common questions, reducing the need for users to search extensively.
User Experience: Simplifies navigation and improves usability by offering instant solutions to queries users may have.
Customer Support: Frees up customer service resources by preemptively addressing common issues, thereby enhancing overall satisfaction and reducing support requests.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aradhyajha** [comment]
@ayush-t02 sir... i want to work on that issue please assign this task to me

**Comment by taniya542** [comment]
@ayush-t02 Please assign me this issue under GSSOC 24.

**Comment by ayush-t02** [comment]
will you add the FAQs page as well?

**Comment by taniya542** [comment]
Yeah Sure, Before tmrw eve I'll drop here the FAQs do let me know if any more ques r to be added there apart from them.

**Comment by taniya542** [comment]
@ayush-t02  Are these questions enough?Or if u have some suggestions about more questions?
![WhatsApp Image 2024-06-28 at 10 58 27_318d6edf](https://github.com/ChromeGaming/Dot-Box/assets/143064148/ba94d44b-a3ba-4aaf-ac22-69196d54edb6)
