### ISSUE TITLE
[New Feature]: Adding Navbar in 'About Us' page

### ISSUE THREAD

**Issue by Kcode15** [ChromeGaming/Dot-Box#420]
### 🎮 feature Request

feature logic and basic description:
Adding a navbar to the About Us page will make it easier for users to navigate the website.

![image](https://github.com/ChromeGaming/Dot-Box/assets/129003839/09b12786-da64-4eac-9575-9372306d3f66)

### Point down the features

feature points:
The navbar will be same as on the other pages

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by JagjeetChauhan** [comment]
@ayush-t02 can you assign this task to me.

**Comment by Kcode15** [comment]
@ayush-t02 please assign me this issue
