### ISSUE TITLE
[Bug]:removing nav bar from footer

### ISSUE THREAD

**Issue by Prakrati1907** [ChromeGaming/Dot-Box#432]
### Give a brief about the bug ✍️

footer also consists of navbar, which is repetetive, removing it

### What is the expected behavior? 🤔

duplication of navbar

### Provide step by step information reproduce the bug 📄

editing the code
![Screenshot 2024-06-30 151311](https://github.com/ChromeGaming/Dot-Box/assets/120261907/7f71b78d-8958-408a-827d-fafb37a26109)
@ayush-t02 pls assign this to me

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
this has been modified with #427
