### ISSUE TITLE
[New Feature]: Redirect to homepage

### ISSUE THREAD

**Issue by partha120804** [ChromeGaming/Dot-Box#445]
## feature logic and basic description:
The game currently stays at the game.html page after winning/losing

I want to add a option that pops up after winning /losing with option to go back to main menu

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by LyubomirT** [comment]
I'd like to work on this issue, please assign me. Glad to contribute to this project!

**Comment by partha120804** [comment]
@ayush-t02 please check this issue and assign me 😄
