### ISSUE TITLE
[Enhancement]: Making the game to start in new window after pressing lets go

### ISSUE THREAD

**Issue by Saipradyumnagoud** [ChromeGaming/Dot-Box#452]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: 
Making the game to start in the new page when the lets go is clicked

### Describe the solution you'd like

Solution steps:
Changing the target of the page

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Saipradyumnagoud** [comment]
@ayush-t02 Please assign me this issue

**Comment by Saipradyumnagoud** [comment]
assign

**Comment by Saipradyumnagoud** [comment]
self

**Comment by MoonStar05** [comment]
Hello 
Can u assign this issue to me under GSSOC'24 label
