### ISSUE TITLE
[New Feature]:Enhancing UI of home page

### ISSUE THREAD

**Issue by ananya-dhiman** [ChromeGaming/Dot-Box#455]
### 🎮 feature Request

Enhancing UI of Home page

### Point down the features

Adding new fonts
Alignment changes in hover of select theme
Making the colour theme consistent

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Shashank061103** [comment]
I would Like to work on this project. Please assign it to me.
