### ISSUE TITLE
[Bug]: When both have same score , if match ends it should give as tie / draw

### ISSUE THREAD

**Issue by srinidhifd** [ChromeGaming/Dot-Box#458]
### Give a brief about the bug ✍️

When both players have the same score if the match has ended, it shows one of the players has won 
![before-fix-ui](https://github.com/ChromeGaming/Dot-Box/assets/93462562/54d6b3a7-fbe6-4e7a-89e8-6ad396c72d63)

### What is the expected behavior? 🤔

It should show as Match tied / Draw instead of Player win

### Provide step by step information reproduce the bug 📄

So when scores are leveled i.e player1_score ==player2_score it should be declared as draw / Match tied, not as player win 

@ayush-t02 please look into this issue .  and I would like to work on this issue . please assign me this under GSSOC'24 label

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by partha120804** [comment]
if the match ends and both have same points then the one who secured most points first should be the winner, I think the game already is showing that 🤔

**Comment by srinidhifd** [comment]
> if the match ends and both have the same points then the one who secured the most points first should be the winner, I think the game already is showing that 🤔

@partha120804 yes it is doing it I agree, But what I was saying is if Both have the same points it must be a draw or tie right, how can you say one who scored the highest points first is the winner, I might be wrong. Let @ayush-t02 take the decision I don't have a problem if it is what you were saying.  

@ayush-t02  take a call on this if its right allow me to continue or unassign this and close it . 
Thank you

**Comment by partha120804** [comment]
you should add this actually, showing a tie/draw options sounds good

**Comment by ayush-t02** [comment]
@srinidhifd continue to work on this as you planned.

**Comment by hars-21** [comment]
Hey @ayush-t02 Please assign me this issue

**Comment by srinidhifd** [comment]
@ayush-t02  actually i am busy in academic work , I wont be able to give time for this . If anyone is interested please assign them this task .

**Comment by srinidhifd** [comment]
@hars-21 Great work! It is working as expected.

**Comment by hars-21** [comment]
thanks!
