### ISSUE TITLE
[Bug]:  Home button on FAQ page is not behaving properly

### ISSUE THREAD

**Issue by partha120804** [ChromeGaming/Dot-Box#499]
### Give a brief about the bug ✍️

![image](https://github.com/user-attachments/assets/972b9375-8d59-459b-bfd7-71222f8a2549)

### What is the expected behavior? 🤔

The home button should always be located at the end of the page

### Provide step by step information reproduce the bug 📄

expand 3 or more FAQ panels and you will see the home button ovelapping the faqs

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by partha120804** [comment]
@ayush-t02 please assign me this issue

**Comment by ayush-t02** [comment]
a similar issue #526 has already been assigned
