### ISSUE TITLE
PLAIN BACKGROUND -MAIN PAGE

### ISSUE THREAD

**Issue by Nih1tGupta** [ChromeGaming/Dot-Box#52]
### 🎮 feature Request

 Background of main page is plain white with no image.

### Point down the features

By adding  a Background image can significantly enhance the visual appeal of a webpage. It will allow others to  incorporate visually engaging elements such as textures, patterns or  illustrations that complement the overall design theme.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Nih1tGupta** [comment]
Can you please assign this to me, I'm eager to contribute and would love working on this under GSSoC'24.

**Comment by SamarupBhattacharya** [comment]
I am a contributor of GSSoC 24, I can complete this task if you assign it to me

**Comment by ujj654** [comment]
Hello @Nih1tGupta, Please assign this issue to me. I could fix this issue.   #GSSoc'24

**Comment by ujj654** [comment]
Hello @Durgesh4993 , Please assign this issue to me. I could fix this issue. #GSSoc'24

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by Rashi563** [comment]
Please assign me this issue

**Comment by 39palakved** [comment]
I WOULD LIKE TO SOLVE THIS ISSUE . PLEASE ASSIGN THIS TASK TO ME
