### ISSUE TITLE
[Bug]: The tile overflows and covers up the header

### ISSUE THREAD

**Issue by Lovelyfin00** [ChromeGaming/Dot-Box#522]
### Give a brief about the bug ✍️

The title section that has name of the game covers up the header/nav section

<br/>
</br>

![image](https://github.com/user-attachments/assets/6915fa3c-d28a-4dce-a8dd-791df11160de)

### What is the expected behavior? 🤔

It is supposed to be on the left and not overflow. Someone should confirm if this behaviour occurs on their end

### Provide step by step information reproduce the bug 📄

Run the app by right-clicking on index.html

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MastanSayyad** [comment]
@Lovelyfin00  Entire Home Page UI is broke, (other pages are working fine)

![image](https://github.com/user-attachments/assets/c62997b4-1fdc-483e-be2e-2b307b5cf8a4)


I would like to try and fix it
