### ISSUE TITLE
[New Feature]: Add Quit Button & Scoreboard Display

### ISSUE THREAD

**Issue by Deekshit7483** [ChromeGaming/Dot-Box#53]
### 🎮 feature Request

Proposal to integrate a "Quit" button for users to exit the game at any point and implement a scoreboard displaying the top six rankings (1st to 6th place) post-game completion, enhancing user experience and providing clearer performance feedback.

assign me under #GSSoC24

### Point down the features

Integrate "Quit" button UI.
Implement functionality for smooth game exit.
Develop scoreboard logic for top six rankings.
Test across devices for reliability.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by geeky2502** [comment]
Can you please assign this issue to me @Deekshit7483

**Comment by MahadevprasadDL** [comment]
I Would like to work on this issue. please assign this task to me @Deekshit7483

**Comment by Durgesh4993** [comment]
@MahadevprasadDL @geeky2502 Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by voiiiiid** [comment]
please assign this issue to me
