### ISSUE TITLE
[Bug]: Setting the Home Page

### ISSUE THREAD

**Issue by Ojas-Arora** [ChromeGaming/Dot-Box#530]
### Give a brief about the bug ✍️

@ayush-t02 The home Page of the website is not properly set. I want to set the Page back and if u could share the picture of the Home Page u need to have for your website or I will do on my own. Kindly assign me this issue.

### What is the expected behavior? 🤔

![image](https://github.com/user-attachments/assets/f9a72059-577a-4188-ab32-2024a01e5b7b)

### Provide step by step information reproduce the bug 📄

I will try to  ake the page look like having navbars with links in the header and footer or else what the project admin wants the page to look like I will make like that.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
this issue has been resolved by #533
