### ISSUE TITLE
Feature✨ :  Improving the FAQ page's Functionalities

### ISSUE THREAD

**Issue by Tejashri-Taral** [ChromeGaming/Dot-Box#532]
### 🎮 feature Request

I want to improve the functionality of the FAQ Page...

Currently the Accordian functionality of the page is not working 
I.e, on opening one answer, other answers are also opening, This should be resolved.

Also, I want to Align the "Home" button properly, Currently it is not aligned with the FAQ Page and is overlapping

### Point down the features

At a time only one answer should be displayed nd all other answers should be hidden until then.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by geeta052** [comment]
🎮 feature Request
Feature✨ : Improving the FAQ page's Functionalities 


Description : 
Enhance the FAQ page with the following features for better user interaction and experience :

FAQ Toggle: Dynamic expansion and collapse with icon changes.
Search Bar: Real-time search to filter FAQ items.
Feedback Buttons: Options for users to rate FAQ usefulness.
Visual and Animation Enhancements: Improved styling and smooth animations.

Select program in which you are contributing
GSSoC24

Code of Conduct
 I follow [CONTRIBUTING GUIDELINE](https://github.com/ChromeGaming/Dot-Box/issues/532) of this project.

**Comment by ayush-t02** [comment]
@Tejashri-Taral do you want to work on this issue?

**Comment by Tejashri-Taral** [comment]
@ayush-t02 , Yes I want to work on it

**Comment by ayush-t02** [comment]
@Tejashri-Taral go on then
