### ISSUE TITLE
Bug:  The Feedback Thank You Pop Up is Not Aligned

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ChromeGaming/Dot-Box#537]
### Give a brief about the bug ✍️

Hey @ayush-t02 

On this website, the feedback thank you pop-up is not aligned.

![image](https://github.com/user-attachments/assets/f264235a-83de-4033-bfb2-09f3fd1461da)

Please assign this issue to me under GSSOC24

### What is the expected behavior? 🤔

It should be properly aligned

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nihasinghania22** [comment]
@ayush-t02 Could you please assign this issue to me

**Comment by ayush-t02** [comment]
@nihasinghania22 it is already assigned, please find some other issue to work on or create a new issue and tag me for assignment.
