### ISSUE TITLE
[New Feature]: Adding Chatbot in the Home Page

### ISSUE THREAD

**Issue by Ojas-Arora** [ChromeGaming/Dot-Box#549]
### 🎮 feature Request

@ayush-t02  I want to add chatbot to the home Page. Kindly assign me this issue.

### Point down the features

This chatbot will help to ask any questions about the website.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@Ojas-Arora bro you tagged the wrong person, this is not my repo

**Comment by Ojas-Arora** [comment]
Oh sorry sir I will do the correction

**Comment by ayush-t02** [comment]
make sure the chatbot is usable on all pages except the gameplay page

**Comment by Ojas-Arora** [comment]
@ayush-t02 ok
