### ISSUE TITLE
[New Feature]:  Add a loader to game

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#558]
### 🎮 feature Request

feature logic and basic description

Add a beautiful loader that will trigger on every page load. 

### Point down the features

feature points

A good ui based loader

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
make sure is loader is not too quick or too slow to load.
