### ISSUE TITLE
[Bug]: Failed to load resource "contributors.css"

### ISSUE THREAD

**Issue by MastanSayyad** [ChromeGaming/Dot-Box#559]
### Give a brief about the bug ✍️

Hey @ayush-t02,

The Contributors page was working fine earlier, but it is now showing an error in the web console: "Failed to load resource 'Contributions.css'."

![image](https://github.com/user-attachments/assets/b9b71067-3cfc-4ec0-ba11-1fb874268a4a)

![image](https://github.com/user-attachments/assets/bd81d024-9be1-4d17-bbdd-1c1d6db0f0ef)

I believe this issue occurred during the process of reverting a pull request. My PR was merged while conflicts were being resolved, which might have caused the problem. Alternatively, the reversion process might have altered the code.

I would like to fix this issue and understand why the CSS file is not loading.

### What is the expected behavior? 🤔

N/A

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
actually on my end things are working fine and no issues with css. Responsive still seems an issue though.

**Comment by MastanSayyad** [comment]
Great! Then I'll try to make it more responsive! also should i just move the css into head style of contributors.html? in this way it will reflect in other people screens also!  @ayush-t02
