### ISSUE TITLE
[New Feature]: Add exit game button

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#560]
### 🎮 feature Request

feature logic and basic description

It will be better to implement a button to exit the game. The user presses the exit game button then an alert will ask for confirmation. If responded yes the current tab(game.html) will close and the user will return to home page.

### Point down the features

feature points

A new button implementation to exit the game.
Confirming the exit will navigate the user back to home page and closes the game tab.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
instead of an exit button, you can work on surrender buttons for both users. whoever surrenders loses

**Comment by hars-21** [comment]
@ayush-t02 Assign it to me. I'll work on surrender button.
