### ISSUE TITLE
[Bug]: Contributors Page is fully bugged

### ISSUE THREAD

**Issue by ayush-t02** [ChromeGaming/Dot-Box#562]
### Give a brief about the bug ✍️

entire page is messed up

![image](https://github.com/user-attachments/assets/288b71a5-f7e1-475d-a88d-b6cb53164b16)

### What is the expected behavior? 🤔

two different contributors page should not overlap

### Provide step by step information reproduce the bug 📄

just open the contributors page

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MastanSayyad** [comment]
Hey @ayush-t02  while adding the chatbot the respective contributor merged both old and new changes to avoid merge conflicts which leaded this overlapping, please assign it to me, I will fix it and restore the Ui,

**Comment by MastanSayyad** [comment]
But we have to rebuild as i have already update the branch with these changes, we have to recreate the Ui

**Comment by ayush-t02** [comment]
@MastanSayyad yup I understand it is because of the chatbot, a lot of other bugs are present now all thanks to the chatbot
