### ISSUE TITLE
Enhancing contributors page, on that page two logos 

### ISSUE THREAD

**Issue by 19sandhya** [ChromeGaming/Dot-Box#565]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

on contributors page two logos are present , also all the contributors images are out box .

### Describe the solution you'd like

remove dublication of logo. also enclosing all contributors image in bx.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by 19sandhya** [comment]
Please assign me this to contribute in this project under GSSOC24

**Comment by ayush-t02** [comment]
@19sandhya this already being worked upon via issue #562 . Please work on something else
