### ISSUE TITLE
[New Feature]: Redesigning the license page

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Dot-Box#580]
### 🎮 feature Request

I want to redesign to make it look like more of a gaming webpage

### Point down the features

I want to redesign to make it look like more of a gaming webpage

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Monika3002** [comment]
Thank you for opening this issue.I want to make the license page more attractive.Can you please assign this to me

**Comment by ayush-848** [comment]
> Thank you for opening this issue.I want to make the license page more attractive.Can you please assign this to me

@Monika3002 I have created this issue to solve it. Please choose another

**Comment by ayush-848** [comment]
@ayush-t02 Please assign this issue to me
