### ISSUE TITLE
➕Enhancement: Improve the UI and Functionality of the FeedbackForm!

### ISSUE THREAD

**Issue by aslams2020** [ChromeGaming/Dot-Box#588]
### 🎮 feature Request

Hey @ayush-t02,

I would like to Completely Enhance the UI of the Websites' Feedback Form
**Current Feedbackform -** 
![image](https://github.com/user-attachments/assets/c30b279b-2ca5-47f1-a9a7-67e4025f1817)

### Here's What Will I Do - 
1. **Completely Changed the Alignment** of the Feedback Form.
2. Add **Shining "Text Shadow" to all the labels**
3. **Add "SVG icons" in front of the labels** to improve the user experience
5. **Improved the "Star-Rating" System** with Much better hovering effects and styling
6. **Changed the Wordings** of the Feedback form.
7. Add a "Back" Button to Exit the Feedbacck form

For ex.(My Prev Work)
![image](https://github.com/user-attachments/assets/3e2bebb4-76a3-4efa-a99d-8f7eaa5778cd)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
this is already done via #555
