### ISSUE TITLE
BUG: Back to Home Button is Overlapping to the Licensing

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ChromeGaming/Dot-Box#604]
### Give a brief about the bug ✍️

Hey @ayush-t02 

On this website back to home button is overlapping to the licensing

![image](https://github.com/user-attachments/assets/9e207e9b-398b-478e-9915-0c3c88a039f0)

![image](https://github.com/user-attachments/assets/ff297a8b-5c70-4f5e-a596-906a606cb13f)

![image](https://github.com/user-attachments/assets/986712af-782f-454f-873b-7c6802cbeca0)

### What is the expected behavior? 🤔

N/A

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
just remove this home button and replace it with something better, then continue with responsiveness
