### ISSUE TITLE
[Enhancement]: Adding a 30s timer to next player move 

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Dot-Box#607]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

If P1 does not move in 30s then the control will go to the next player

### Describe the solution you'd like

If P1 does not move in 30s then the control will go to the next player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Shreya-1305** [comment]
I want to work on this issues. Please assign me this issue

**Comment by Shreya-1305** [comment]
@ChromeGaming can i work on this issue?

**Comment by ayush-t02** [comment]
@ayush-848 do you want to work on this issue?

**Comment by ayush-848** [comment]
> @ayush-848 do you want to work on this issue?

Yes obviously 
I thought of this idea at first

**Comment by Shreya-1305** [comment]
I am sorry , but @ayush-t02 can you please tell me if my way to fix this was correct or not . As I am a new learner and this was my first try to contribute to opensource. Thankyou

**Comment by ayush-t02** [comment]
Hello @Shreya-1305, you did really well with your PR, code was clean and crisp. 

In general, when it comes to open source your approach of working is perfect, that is by asking to work on issues created by others but since this GSSoC has become kind of a race that approach is not working here. So, please find some bug in the current game or think of new feature enhancements and create a new issue. Do tag me for assignment.

**Comment by ayush-t02** [comment]
@ayush-848 do not specify what is obvious and not. If you want to work on an issue specify it in the issue body or comments. When you work on good open source projects a lot of issues are solved by people who do not create them.

**Comment by ayush-848** [comment]
> @ayush-848 do not specify what is obvious and not. If you want to work on an issue specify it in the issue body or comments. When you work on good open source projects a lot of issues are solved by people who do not create them.

Yes @ayush-t02 I agree with you and I also agree my choice of words could have been better

**Comment by Shreya-1305** [comment]
thankyou @ayush-t02, for reviewing my code . This was my first try and hoped for it to get merged , but your response is really motivating . Thankyou very much .
