### ISSUE TITLE
[New Feature]: Enhancing the How to play section

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Dot-Box#608]
### 🎮 feature Request

To style it according to the game theme

### Point down the features

To style it according to the game theme

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@ayush-t02 please assign this issue to me

**Comment by ayush-848** [comment]
@ayush-t02 
![image](https://github.com/user-attachments/assets/71b89865-5ee0-46db-9fe5-0ec4f0a437a0)
what happened here??

**Comment by ayush-t02** [comment]
your timer had caused some issues as told to me by a contributor, I guess this is one of them, someone was working on it.

**Comment by ayush-848** [comment]
> your timer had caused some issues as told to me by a contributor, I guess this is one of them, someone was working on it.

Before pushing the code I didn't find any distortion in 1024px or 768px
I guess pushing into production always gives a bit different result

**Comment by ayush-848** [comment]
> your timer had caused some issues as told to me by a contributor, I guess this is one of them, someone was working on it.

Can you try reverting that one, if that one is responsible
Whole page should not get affected due to a faculty pr
