### ISSUE TITLE
[Enhancement]: Better Hamburger-menu

### ISSUE THREAD

**Issue by VijaySamant4368** [ChromeGaming/Dot-Box#624]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The Hamburger Menu in the howtoplay page looks very bland.
![image](https://github.com/user-attachments/assets/a1ab73a9-0c47-459d-b6d5-d60c39c9cb87)

### Describe the solution you'd like

I will make a better menu for smaller screens.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VijaySamant4368** [comment]
@ayush-t02  please have a look.

**Comment by VijaySamant4368** [comment]
There are many other pages with similar problems. I will resolve them all.

**Comment by VijaySamant4368** [comment]
Something like this:

https://github.com/user-attachments/assets/032e6476-8c4d-4bae-9184-65273a829e85

**Comment by ayush-t02** [comment]
make all the hamburger for all pages uniform

**Comment by VijaySamant4368** [comment]
On it!!

**Comment by VijaySamant4368** [comment]
@ayush-t02 please kindly have a look at the attached pr.
