### ISSUE TITLE
[New Feature]: No Home Icon 

### ISSUE THREAD

**Issue by Ojas-Arora** [ChromeGaming/Dot-Box#636]
### 🎮 feature Request

@ayush-t02 There is no Home icon present now in any page. Kindly assign me this issue.

### Point down the features

Home icon will allow to go back to home page without using the back buttton.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
I asked for it to be removed, it felt very unnecessary and caused responsiveness issue.
