### ISSUE TITLE
[Bug]: Footer bug in FAQ page

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Dot-Box#646]
### Give a brief about the bug ✍️

![image](https://github.com/user-attachments/assets/32274f09-7e77-4588-9e09-852aece59476)

### What is the expected behavior? 🤔

The footer should be styled or not be present here

### Provide step by step information reproduce the bug 📄

https://chromegaming.github.io/Dot-Box/pages/FAQs.html

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@ayush-t02 other pages such as the how to play, privacy policy do not have a footer
So int the FAQ page should the footer remain???

**Comment by ayush-t02** [comment]
no need I think

**Comment by ayush-848** [comment]
> no need I think

Ok
