### ISSUE TITLE
File structuring 

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#652]
### 🎮 feature Request

feature logic and basic description

Restructure files in the codebase
Current html files contains css and js in them 
Update - css will be only in css files and js in js files. 

Files are created according to html but not implemented in the right way.

### Point down the features

feature points

The html, css and js are all in one file. I want to structure in different files that will make the code readable and understandable.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by vivi2004** [comment]
Hey I wants to contribute in the file structuring   would  you please assign me that work so that I can assign  do the works

**Comment by hars-21** [comment]
Hey @ayush-t02 , I have already opened the issue regarding this code structuring. Yet another issue was #673 was created and assigned

**Comment by ayush-t02** [comment]
@hars-21 you work only on the js part since css is already resolved

**Comment by hars-21** [comment]
ok
