### ISSUE TITLE
Fix Scoreboard and Timer

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#655]
### 🎮 feature Request

feature logic and basic description

When we start the game score board overlaps the player details page.

![Screen Shot 2024-07-29 at 10 07 03 PM](https://github.com/user-attachments/assets/755be7c6-13a0-4304-9557-42e5c4bdfee7)

### Point down the features

feature points

Remove scoreboard till the game does not starts and when the game starts put it back.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by vivi2004** [comment]
Hey I wants to contribute in this  works please assign me the work so that I can contribute in this..

**Comment by hars-21** [comment]
@ayush-t02 Also, when playing with 6 players - the scoreboard doesn't fit in the page and creates scroll. 
I want to fix the scoreboard position and alignment. 

![Screen Shot 2024-07-31 at 8 54 05 PM](https://github.com/user-attachments/assets/97f68103-7c5a-4df1-99a8-156b4d2b3840)
![Screen Shot 2024-07-31 at 8 54 08 PM](https://github.com/user-attachments/assets/e88f712b-622b-45ed-9d10-82af4a09ad59)
