### ISSUE TITLE
Add Dynamic Date Functionality to Leagel Pages for Weekly Update and Licensing  Yearly 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ChromeGaming/Dot-Box#661]
### 🎮 feature Request

Hey @ayush-t02 

I would like to Add Dynamic Date Functionality to Leagel Pages for Weekly Update and Licensing  Yearly 

![image](https://github.com/user-attachments/assets/cbf0ec23-b5db-4b62-bf67-91a53de15f39)

![image](https://github.com/user-attachments/assets/2c4a9a41-25c2-4f35-96d5-1625f2103334)

![image](https://github.com/user-attachments/assets/e69dd076-79b9-44bd-909e-3ec1ca17e3ed)

### Point down the features

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by vivi2004** [comment]
Hey @ayush-t02

I would like to Add Dynamic Date Functionality to Leagel Pages for Weekly Update and Licensing Yearly
