### ISSUE TITLE
🌟Improvement: Complete UI and Functionality of FeedbackForm! 

### ISSUE THREAD

**Issue by aslams2020** [ChromeGaming/Dot-Box#664]
### 🎮 feature Request

Hey @ayush-t02 

i have a feature enhancement request to make- 

Currently the feedback form of the website is not well aligned, not styled well to follow the website's game theme.

- The **theme** of the feedback form is **not matching** 
- **There Should not be any Vertical Scrollbar for a feedback form** as it leads to inconsistency
- The **Star Rating System is Enough** for giving the rating, so **there should not be the "Reaction emojis"** 
- The **overall alignment of the input tags is not well aligned**

As you can see here - ( I pointed out some of the issues with the violet colors)
![image](https://github.com/user-attachments/assets/460a7c7f-55b2-4ae2-b994-4cc7845d4cf0)

Please assign me the issue to fully Improve the UI and functionalities to it

### Point down the features

.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aslams2020** [comment]
@ayush-t02 i want to work on this.

**Comment by ayush-t02** [comment]
let the reaction emojis be there
