### ISSUE TITLE
[New Feature]: Improve UI of choosing player section

### ISSUE THREAD

**Issue by sau-mili** [ChromeGaming/Dot-Box#667]
### 🎮 feature Request

feature logic and basic description
Improve the overall Ui including buttons, options, flex

I mean to improve this area:
![image](https://github.com/user-attachments/assets/481635d3-703b-40b0-bcde-0df98d4bc9bf)

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sau-mili** [comment]
Please assign me this

**Comment by sau-mili** [comment]
@ayush-t02 please assign me this

**Comment by ayush-t02** [comment]
this section is already fixed, pull the recent changes

**Comment by sau-mili** [comment]
My issue was unchecked for days. Can you share when you are active? So I will try to raise issue around that time, so that it comes to your notice.
