### ISSUE TITLE
[New Feature]: To add the navbar to every page

### ISSUE THREAD

**Issue by ayush-848** [ChromeGaming/Dot-Box#669]
### 🎮 feature Request

In every page ending, there is the "back to home" button. 
Should i remove that and add the navbar instead????

### Point down the features

Navbar in every page

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@ayush-t02 please check this

**Comment by ayush-t02** [comment]
no need of nav in every page
