### ISSUE TITLE
[Bug]: HTML files have css code even though style is a different folder

### ISSUE THREAD

**Issue by ayush-t02** [ChromeGaming/Dot-Box#673]
### Give a brief about the bug ✍️

All the CSS should be part of the style folder with proper naming as to which file contains which css

### What is the expected behavior? 🤔

All the CSS should be part of the style folder with proper naming as to which file contains which css

### Provide step by step information reproduce the bug 📄

simply open index.html

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-848** [comment]
@ayush-t02 Is it open??

**Comment by ayush-t02** [comment]
nope no error, just cleaning out the code

**Comment by ayush-848** [comment]
> nope no error, just cleaning out the code

ok
