### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [ChromeGaming/Dot-Box#694]
### 🎮 feature Request

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24 @ayush-t02 

### Point down the features

![IMG_20240706_122058](https://github.com/user-attachments/assets/1334f0a4-2eb1-4067-b8c8-3e50fce7747a)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
feedback system is already present
