### ISSUE TITLE
BUG🐞: Update Outdated Tutorial Video on "How to Play" Page

### ISSUE THREAD

**Issue by aslams2020** [ChromeGaming/Dot-Box#697]
### Give a brief about the bug ✍️

Hey @ayush-t02 

The current tutorial video on the "How to Play" page **is outdated** and **does not reflect the new features and functionalities that have been added to the game.** 
To provide a better user experience and ensure that players have the most up-to-date information, the tutorial video needs to be updated.

**Here as you can see -** 

https://github.com/user-attachments/assets/2e8bfd0c-c249-4177-bcef-9126c3e0593c

**Expected Behaviour :** 

The "How to Play" page should feature an updated tutorial video that includes all recent changes, new features, and functionalities added to the game. 
This will help players better understand and engage with the latest version of the game.

**Actual Behaviour :**

The existing tutorial video is outdated and does not cover the new updates and features of the game, leading to potential confusion for players.

Please assign me this issue.
thankyou!

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
update the video in the readme as well

**Comment by aslams2020** [comment]
Sure @ayush-t02 , Will do that!
