### ISSUE TITLE
Bug in Contributors Data Fetching

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ChromeGaming/Dot-Box#712]
### Give a brief about the bug ✍️

Hey @ayush-t02 

In the contributors page contributors.html file the data fetching scripts are missing and we can't see any contributors data over there, also the old scripts were not fetching all contributors data it was only limited to 30 contributors whose contributions are less than 2

![image](https://github.com/user-attachments/assets/186c6c12-e74b-4573-bf2e-c0e429fa459b)

   

### What is the expected behavior? 🤔

N/A

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
it works as of now

**Comment by RadhikaMalpani1702** [comment]
@ayush-t02 It is not showing in deploy link may be it showing local link

**Comment by ayush-t02** [comment]
yup I it noticed too
