### ISSUE TITLE
BUG🐞: Icons Missing in Navbar and Footer on ALL "Non-Home" Pages

### ISSUE THREAD

**Issue by aslams2020** [ChromeGaming/Dot-Box#716]
### Give a brief about the bug ✍️

Hey @ayush-t02 

The icons for each link **present in the navbar and footer** are currently **visible only on the home page.** 
**They are missing on all other pages across the website.** 
This inconsistency affects the user experience and the visual uniformity of the website.

https://github.com/user-attachments/assets/cf28197d-61ea-4fe6-bcfb-bcdb0ed10f00

### What is the expected behavior? 🤔

N/A

### Provide step by step information reproduce the bug 📄

N/A

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shenmareparas** [comment]
Please assign me this issue.
I would like to work on it
