### ISSUE TITLE
[New Feature]: Adding Menu

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#72]
### 🎮 feature Request

feature logic and basic description:
A menu with required buttons on left side

### Point down the features

feature points:
1. Add a menu on the left side for following buttons
2. Home
3. Restart
4. Leaderboard
5. Tournaments

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by MuzhdaN** [comment]
Hi, 

I am GSSOC'24 contributor, I would like to work on this part of your project.  Would you please assign me this issue, if no one has taken it yet?

**Comment by Alokita004** [comment]
Hello @Durgesh4993 sir, i would like to adding the menu in this project please assign me this issue. I would like to work on this part of your project.

**Comment by Durgesh4993** [comment]
@MuzhdaN @Alokita004 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Sid-80** [comment]
@Durgesh4993 I am willing to work on this issue. Please assign me, there is no response since 2 weeks!

**Comment by hars-21** [comment]
Closing this as #700 has been merged
