### ISSUE TITLE
[Bug]: How to Play video not working in howtoplay.html page and readme.md 

### ISSUE THREAD

**Issue by srinidhifd** [ChromeGaming/Dot-Box#720]
### Give a brief about the bug ✍️

Description
1.Latest video of how to play is not working in howtoplay page
2.Latest video of how to play is not working in readme.md
3.Add logo instead of manual text for Maximize Boxes for consistency
4. Star us button not working in about us page
5. Update the readme.md to add recent changes
6.Fix the hidden menu bar in game.html initial page 

### What is the expected behavior? 🤔

Description
1.Latest video of how to play is not working in howtoplay page
2.Latest video of how to play is not working in readme.md
3.Add logo instead of manual text for Maximize Boxes for consistency
4. Star us button not working in about us page
5. Update the readme.md to add recent changes
6.Fix the hidden menu bar in game.html initial page 

### Provide step by step information reproduce the bug 📄

Description
1.I will add working link of video
3.Add logo instead of manual text
4. will update the link for star us
5. I will update the readme.md file
6. I will fix the menubar in game,html

![before-fix-video-howtoplay](https://github.com/user-attachments/assets/e2528d21-108e-4bae-a7af-fcb73c0cfe70)
![before-fix-video-readme](https://github.com/user-attachments/assets/e9317fe3-dca7-4454-ad54-54be3f5dbfed)
![before-fix-logo-howtoplay](https://github.com/user-attachments/assets/1fb4712d-7b35-4cd4-86c8-01aa32573c80)
![before-fix-star-us](https://github.com/user-attachments/assets/07f3a621-d5be-405d-abad-16b7846166e6)
![before-fix-game html](https://github.com/user-attachments/assets/de30a814-afb8-4b2e-95ef-8a5b722c52ab)

@ayush-t02 please assign the issue to me under gssoc with appropriate label .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by ayush-t02** [comment]
video seems to working in the howtoplay page, as for the readme, I'll just inform the contributor because I merged the PR today itself.
