### ISSUE TITLE
[Enhancement]: Making the Overall app UI more attractive

### ISSUE THREAD

**Issue by Khanishsuresh** [ChromeGaming/Dot-Box#73]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Making the UI more attractive and user-friendly would make the project more attractive to many users 

### Describe the solution you'd like

Solution steps

->By changing the backgrounds which makes the UI attractive
->Then changing the styles of all the input fields , Buttons
->Then some animations when a user is won 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by moroii69** [comment]
> ### Do you want to have the enhancement of existing game ? 😀 Describe yourself..
> Making the UI more attractive and user-friendly would make the project more attractive to many users
> 
> ### Describe the solution you'd like
> Solution steps
> 
> ->By changing the backgrounds which makes the UI attractive ->Then changing the styles of all the input fields , Buttons ->Then some animations when a user is won
> 
> ### Select program in which you are contributing
> _No response_
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

### please provide more details regarding the design idea you're looking for. im open to collaborate on this issue.

**Comment by Khanishsuresh** [comment]
Hii @Durgesh4993 ,

As a GSSOC'24 contributor, I would like to contribute to your project. Would you please assign me this issue?
