### ISSUE TITLE
[Bug]: Music should be on by default

### ISSUE THREAD

**Issue by ayush-t02** [ChromeGaming/Dot-Box#731]
### Give a brief about the bug ✍️

when the webapp is opened, the music is not playing by default

### What is the expected behavior? 🤔

music should be playing from the start with the option of turning it off available

### Provide step by step information reproduce the bug 📄

just open the application

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by hars-21** [comment]
assign it to me
