### ISSUE TITLE
Improve about us page

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#747]
### 🎮 feature Request

Improve the current about us page
Some icons are not rendering
Extra space is available which is not needed

### Point down the features

Enhancing about us page
Fixing icon render
eliminating the extra space
making responsive
add new animation

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by hars-21** [comment]
@ayush-t02 Please assign it to me and I already made a PR for this, Please merge it!!!!

**Comment by ayush-t02** [comment]
@hars-21  ok!!!! 🤣
