### ISSUE TITLE
[Enhancement]: Win popup

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#75]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement - After any player wins a popup will be displayed showing the player win and score. Also, a play again and home button will be displayed.

### Describe the solution you'd like

Solution steps:
1. add a popup with player name and score
2. add play again and home buttons
3.  a good animation for good user experience
4.  adding a sound for win like clapping, horn or some other.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by hars-21** [comment]
Please assign this issue to me under gssoc24

**Comment by Durgesh4993** [comment]
Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Durgesh4993** [comment]
@hars-21 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by hars-21** [comment]
When any player wins, the player name just plays a animation.
I want to change it to a window where Player name - wins will be written and further option to play again or back to home will be displayed along with score of that player.

**Comment by grasyPatel** [comment]
Hello @Durgesh4993 , i want to work on this issue ,kindly assign me .

**Comment by Deepthi-Ramineni** [comment]
Can you please assign this to me under GSSOC'24.....??? I am very much interested in doing this....
