### ISSUE TITLE
[Bug]: Wrong nav-link address in the home page

### ISSUE THREAD

**Issue by VijaySamant4368** [ChromeGaming/Dot-Box#769]
### Give a brief about the bug ✍️

The link to different pages in the home page is wronh.

### What is the expected behavior? 🤔

The address should be corrected 

### Provide step by step information reproduce the bug 📄

https://github.com/user-attachments/assets/14b8a687-ce36-46a9-b0cc-e9ae89908939

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by VijaySamant4368** [comment]
@ayush-t02 please look into this.

**Comment by ayush-t02** [comment]
which link is this
