### ISSUE TITLE
[New Feature]: Add loader

### ISSUE THREAD

**Issue by hars-21** [ChromeGaming/Dot-Box#83]
### 🎮 feature Request

feature logic and basic description
Adding a loader to a website before opening the landing page and before board loads.
this will enhance user experience and maintain good workflow

### Point down the features

feature points
1. Adding Preloader
2. adding loader before game starts
3. UI enhancement

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
