### ISSUE TITLE
[New Feature]: Add Dark Mode

### ISSUE THREAD

**Issue by moroii69** [ChromeGaming/Dot-Box#95]
### 🎮 feature Request

- dark mode functionality can be added for both home page and game page (interchangeable between dark and light modes with a toggle button).
- styles can be updated for various elements across the application to ensure consistency and readability in both light and dark modes.

### Point down the features

![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/74895423/305059cc-e79e-47e4-a821-15d5e56cd202)
![image](https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/74895423/52c09053-2767-4f66-b51f-bd0c250d2943)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kgourab73** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by Akansha1409** [comment]
Hey, there! , i think it is a great project
I want to make it more attractive by adding dark theme
kindly assign me this issue.

**Comment by Tarani12** [comment]
I would like to work on this issue. Can you please assign me this task
