### ISSUE TITLE
[New Feature]: Enhancement Request: Improve Clarity and Detail of Game Instructions

### ISSUE THREAD

**Issue by kvdevlopment** [ChromeGaming/Dot-Box#99]
### 🎮 feature Request

feature logic and basic description
**Description:**
Your instructions provide a solid foundation for understanding the game rules, but there are opportunities for enhancement to ensure players grasp the mechanics fully. Here are some suggested improvements:

**Clarify Winning Condition: **Specify what constitutes a "box" to avoid confusion. For example, explain that a box is formed when a player completes the fourth side of a square on the grid.

**Provide Example:** Include a simple example or illustration to help players visualize how the game works in practice. This could involve a diagram showing how boxes are formed on the grid and how the score is calculated.

**Emphasize Turn Mechanics:** Reinforce the point about players switching turns after every move. Clarify how turns are determined, such as by clockwise rotation or alternate turns.

**Highlight Extra Chance Rule:** Give more emphasis to the rule about the player who fills the last box receiving an extra turn. Consider providing a separate bullet point or section to ensure this rule is clearly understood.

**Language Consistency:** Ensure consistency in language usage throughout the instructions. For example, maintain consistent terminology like "maximum number of boxes" and "filled the last box" for clarity.

### Point down the features

feature points
Clarified Winning Condition: Specify that a "box" is formed when a player completes the fourth side of a square on the grid, ensuring players understand the objective clearly.

Illustrative Example: Provide a visual example or diagram demonstrating how boxes are formed on the grid and how scoring is calculated, aiding players in grasping the game's mechanics more intuitively.

Reiterated Turn Mechanics: Reinforce the understanding of turn mechanics by restating that players switch turns after every move, with play typically rotating in a clockwise direction or based on alternate turns.

Emphasized Extra Chance Rule: Highlight the rule about the player who completes the last box receiving an additional turn, possibly with a dedicated section or bullet point to ensure players are aware of this important gameplay aspect.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by kvdevlopment** [comment]
Hello @Durgesh4993
Assign me this issue

**Comment by ShravaniPathak** [comment]
I would like to work on this issue. Please assign this task to me
